quarkus.http.port=8080
quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:4200
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=accept,content-type,origin


# OpenAPI and Swagger UI configuration
quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.info.title=LabSeq API
quarkus.smallrye-openapi.info.version=1.0.0
quarkus.smallrye-openapi.info.description=API documentation for LabSeq app


